import "./globals.css"

export const metadata = {
  title: "Next App with ChatGPT + DALL-E",
  description: "Generated by Felipe França",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body>{children}</body>
    </html>
  )
}
